# data c storage

categories_dict = {
    1: "Электроника",
    2: "Бытовая техника",
    3: "Компьютерная техника", 
    4: "Мебель",
    5: "Одежда",
    6: "Обувь",
    7: "Продукты питания",
    8: "Инструменты",
    9: "Строительные материалы",
    10: "Автозапчасти",
    11: "Спорттовары",
    12: "Канцтовары",
    13: "Книги",
    14: "Игрушки",
    15: "Хозтовары",
    16: "Косметика",
    17: "Медицинские товары",
    18: "Ювелирные изделия",
    19: "Часы",
    20: "Сумки и аксессуары",
    21: "Товары для дома",
    22: "Садовый инвентарь",
    23: "Офисное оборудование",
    24: "Сетевое оборудование",
    25: "Фото- и видеотехника",
    26: "Аудиотехника",
    27: "Игры и консоли",
    28: "Музыкальные инструменты",
    29: "Товары для животных",
    30: "Туристическое снаряжение",
    31: "Рыболовные товары",
    32: "Охотничьи товары",
    33: "Велосипеды и аксессуары",
    34: "Автоаксессуары",
    35: "Мототехника",
    36: "Лодки и катера",
    37: "Стройтехника",
    38: "Промышленное оборудование",
    39: "Медицинское оборудование",
    40: "Образовательные товары",
    41: "Химическая продукция",
    42: "Текстиль и ткани",
    43: "Посуда и кухонные принадлежности",
    44: "Вино и алкоголь",
    45: "Табачные изделия",
    46: "Цифровые товары",
    47: "Сельхозтехника",
    48: "Металлопрокат",
    49: "Электротехника",
    50: "Сантехника"
}

key_api='eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwbDgxLVYyWUNyQ1V0bmVRTWxxRUNmSVluS1Z3VExnQVIwZXhiTkF1SF9nIn0.eyJleHAiOjIwNzUxMzc3NDcsImlhdCI6MTc1OTc3NzgxOCwiYXV0aF90aW1lIjoxNzU5Nzc3NzQ3LCJqdGkiOiJlZjYzNzcwYi03YjcyLTQ1M2UtYWFiMS0wZDYwMzY0YjBiNTQiLCJpc3MiOiJodHRwczovL3pha3Vwa2kubW9zLnJ1L2F1dGgvcmVhbG1zL1BwUmVhbG0iLCJhdWQiOiJJbnRlZ3JhdGlvbkFwcCIsInN1YiI6IjdlMjhiZTU5LWYyNjYtNGNkZi05OWJhLTMzYzJmYTFmZWY4ZSIsInR5cCI6IkJlYXJlciIsImF6cCI6IlBwQXBwIiwic2Vzc2lvbl9zdGF0ZSI6ImViMGNmYzIzLWJjYmQtNDg1NS05OWRlLTkyNmY1Y2VkNmEyZiIsInNjb3BlIjoiSW50ZWdyYXRpb25TY29wZSIsInNpZCI6ImViMGNmYzIzLWJjYmQtNDg1NS05OWRlLTkyNmY1Y2VkNmEyZiJ9.ZJT5EnlbNip9C3yp_nCOmUfXPETQACO3v-1_FUAFZSTrjlc6F8PBRPpRToerFT4EWD1yndB5mkeMQ4XeYSEhvJ4ysDO4UUWSNPtQKDgHuBR03NbGOROKomI1YQq4-hHS5r_-O5bAsHEqWuSQTpvTDGhnns51IsQwo9FI56y26DS73j4NXSWl5OF1riQ0djahXTsB-psWVzvIsJrhNuvNOuDHyDElpBOiMLas6tjMfCVmL9fxrS5h4I4gKPLHmFaamdcy8Nl054gi6q9jFAppyZSjxIJdu7f9QgZc2CjxYenp7eOqkQzL_ThAoMPfvwExvBgoGWHh3i6pPnubkVOwPw'