# data c storage

categories_dict = {
    1: "Электроника",
    2: "Бытовая техника",
    3: "Компьютерная техника", 
    4: "Мебель",
    5: "Одежда",
    6: "Обувь",
    7: "Продукты питания",
    8: "Инструменты",
    9: "Строительные материалы",
    10: "Автозапчасти",
    11: "Спорттовары",
    12: "Канцтовары",
    13: "Книги",
    14: "Игрушки",
    15: "Хозтовары",
    16: "Косметика",
    17: "Медицинские товары",
    18: "Ювелирные изделия",
    19: "Часы",
    20: "Сумки и аксессуары",
    21: "Товары для дома",
    22: "Садовый инвентарь",
    23: "Офисное оборудование",
    24: "Сетевое оборудование",
    25: "Фото- и видеотехника",
    26: "Аудиотехника",
    27: "Игры и консоли",
    28: "Музыкальные инструменты",
    29: "Товары для животных",
    30: "Туристическое снаряжение",
    31: "Рыболовные товары",
    32: "Охотничьи товары",
    33: "Велосипеды и аксессуары",
    34: "Автоаксессуары",
    35: "Мототехника",
    36: "Лодки и катера",
    37: "Стройтехника",
    38: "Промышленное оборудование",
    39: "Медицинское оборудование",
    40: "Образовательные товары",
    41: "Химическая продукция",
    42: "Текстиль и ткани",
    43: "Посуда и кухонные принадлежности",
    44: "Вино и алкоголь",
    45: "Табачные изделия",
    46: "Цифровые товары",
    47: "Сельхозтехника",
    48: "Металлопрокат",
    49: "Электротехника",
    50: "Сантехника"
}

key_api='eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwbDgxLVYyWUNyQ1V0bmVRTWxxRUNmSVluS1Z3VExnQVIwZXhiTkF1SF9nIn0.eyJleHAiOjIwNzQ4MzM1MTcsImlhdCI6MTc1OTQ3NTIyMCwiYXV0aF90aW1lIjoxNzU5NDczNTE3LCJqdGkiOiIyNThmYTAzZi1jNTk5LTQ5MTUtOWUzYS0yMDdhMmYxOWVmNjYiLCJpc3MiOiJodHRwczovL3pha3Vwa2kubW9zLnJ1L2F1dGgvcmVhbG1zL1BwUmVhbG0iLCJhdWQiOiJJbnRlZ3JhdGlvbkFwcCIsInN1YiI6IjdlMjhiZTU5LWYyNjYtNGNkZi05OWJhLTMzYzJmYTFmZWY4ZSIsInR5cCI6IkJlYXJlciIsImF6cCI6IlBwQXBwIiwic2Vzc2lvbl9zdGF0ZSI6IjNkOTc1N2FhLTNlNjEtNGY5Ni1hNGIzLWE4NjMxNTk3YjVkMiIsInNjb3BlIjoiSW50ZWdyYXRpb25TY29wZSIsInNpZCI6IjNkOTc1N2FhLTNlNjEtNGY5Ni1hNGIzLWE4NjMxNTk3YjVkMiJ9.CREupv9Bav92I17mb62RwVqYIWH2kwaHGL4W9kNDXmvKSvK2jSio1skOGe_UjsmIzTrusEU4h8L9XuPZB-ILBDe3GANNsT4fF5WUWjHWjpeULpSa5Z7SijcPAQ-0S1tX734ysPwfT4N4_bsOzew-h7eMYaxTfH5PvXvI8ht73UCC0m8yKL_pufHt1y7HvjZ6ZpuW4AnyBnQdcmULMS9ufzU6KnH7QkDSiAUF-Xajpe-N2AyWBwdunmMtQ9sSGPPExYVzmqHzKWGdrQuqRmymAyvRfs9Cx12Sf7jpD4-aOwwu7gKfMaE6-2GypETFglGXPr3Y6EEUMpxyTbWljFP-rg'